[workspace]
resolver = "2"
members = ["ast_generator", "oxa"]

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
debug = 0
strip = "symbols"
opt-level = 3

[profile.dev]
opt-level = 1
debug = true

[profile.dev.package."*"]
opt-level = 3

[profile.bench]
debug = true
